### PR TITLE
Builders eggsactly

### PR DESCRIPTION
**Pull request by eggsactly**
Below are the additions to the new GHDL web page:
- Height of the main container no longer fixed to the height of the screen. Scrolling enabled for all screen sizes.
- Carousel dynamically chooses the number of slides based on the width of the screen. 
- Increased padding around the links on the navigation page to make it easier to click on for small screens.
- Made logo more prominent

### CODE REVIEW

**Comment by eine** [comment]
Thanks! I'm out during this week, so I don't know if I will be able to review it properly. If not, I will do it the following weekend.

**Comment by eggsactly** [comment]
@1138-4EB Alright. Review it at your leisure, just wanted to help!

**Comment by eggsactly** [comment]
@1138-4EB Do you plan on using the changes I made to the GHDL site?

**Comment by eine** [comment]
Sure. I was busy on January and then forgot about it. I'm so sorry. I am having dinner now and I'll then do the merge/rebase.

**Comment by eggsactly** [comment]
@1138-4EB Thanks! I did another merge with my builders-eggsactly branch with builders and I've looked again at the changes I made. I realized that although I accomplished the task of making the carousel width dynamic, I did it with JavaScript. It would have been better to use CSS based methods. 

I've been thinking whether the design of the page is good to start with. I found out that carousels are derided in web design because [users ignore the content in them](https://www.nngroup.com/articles/designing-effective-carousels/) and because [they're usually added to a site for business needs and not for user needs](https://webflow.com/blog/carousel-slider-design-best-practices). I think a better design would be to put all content onto a dynamic width grid with no animation that the user can scroll through and implement it only with HTML/CSS (no JavaScript). What do you think?

**Comment by eine** [comment]
I completely agree with you. Just hold your changes for half an hour or so:

- I will merge/rebase your changes again.
- We will close this issue.
- You will checkout branch `frontpage` (which I have not created yet).
- We will work on `index.html` in branch `frontpage`.

This is because branch `builders` contains additional content that is not relevant, and I'd like to keep it split.

**Comment by eine** [comment]
It is ready now. Thanks @eggsactly!

https://travis-ci.org/1138-4EB/ghdl/builds/366577901
https://1138-4eb.github.io/ghdl/doc/builders/about.html

**Comment by eggsactly** [comment]
@1138-4EB Thank you.

**Pull request closed without merging**
